import { Session, getServerSession } from "next-auth";
import DLayout from "./components/DLayout";
import Providers from "@/components/Providers";
import { authOptions } from "../api/auth/[...nextauth]/route";

export const metadata = {
  title: "Dashboard Page",
  description: "Generated by create next app",
};

export default async function DashboardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="en">
      <body>
        <Providers>
          <DLayout session={session}>{children}</DLayout>
        </Providers>
      </body>
    </html>
  );
}
